<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ifstatement" nsURI="http://ifstatement/" nsPrefix="ifstatement">
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="../../SimpleIMP/model/SimpleIMP.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="ecore:EClass ../../SimpleIMP/model/SimpleIMP.ecore#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thn" lowerBound="1" eType="ecore:EClass ../../SimpleIMP/model/SimpleIMP.ecore#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="els" eType="ecore:EClass ../../SimpleIMP/model/SimpleIMP.ecore#//Block"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
